CandyStoreWeb/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CandyStoreWeb.Models
{
    public sealed class User
    {
        private static User user;

        public string Name { get; set; }

        public string Role { get; set; }

        private User(string name, string role)
        {
            this.Name = name;
            this.Role = role;
        }

        public static User SetCurrentUser(string name, string role)
        {
            if(user == null)
            {
                user = new User(name, role);
            }
            return user;
        }   

        public static User CurrentUser
        {
            get
            {
                return user;
            }
        }

        public static void DeleteCurrentUser()
        {
            if(user != null)
            {
                user = null;
            }
        }
        
    }
}

CandyStoreWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DAL;

namespace CandyStoreWeb.Controllers
{
    public class HomeController : Controller
    {

        DBOperations db = new DBOperations();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(string login, string password)
        {
            var user = db.GetAllEmployees().Where(emp => emp.Login == login && emp.PasswordHash == Tools.Base64Encode(password)).FirstOrDefault();
            if (user == null)
            {
                return RedirectToAction("SignIn");
            }
            else
            { 
                Models.User.SetCurrentUser(user.Login, user.Role);
                return RedirectToAction("Index");
            }
        }

        public ActionResult SignOut()
        {
            Models.User.DeleteCurrentUser();
            return RedirectToAction("Index");
        }
    }
}

CandyStoreWeb/Controllers/OrdersController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CandyStoreWeb.Controllers
{
    public class OrdersController : Controller
    {
        DBOperations db = new DBOperations();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.GetAllOrders();
            return View(orders);
        }

        public ActionResult Create()
        {
			var stockPastries = db.GetAllPastries().Where(pastr => pastr.Stock_ID != null).ToList();

			//stockPastries.Add(new DAL.Pastry()
			//{
			//	PastryType = new DAL.PastryType()
			//	{
			//		Name = "Торт",
			//		ID = 1,
			//	},
			//	ID = 1,
			//	Price = 10,
			//	Quantity = 4,
			//	ShelfLife = 30

			//});
			//stockPastries.Add(new DAL.Pastry()
			//{
			//	PastryType = new DAL.PastryType()
			//	{
			//		Name = "Конфета",
			//		ID = 1,
			//	},
			//	ID = 2,
			//	Price = 120,
			//	Quantity = 40,
			//	ShelfLife = 30

			//});

			return View(stockPastries);
        }

        [HttpPost]
        public ActionResult Create(List<DAL.Pastry> pastries)
        {
            return RedirectToAction("Index");
        }
    }
}

CandyStoreWeb/Controllers/PastriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DAL;

namespace CandyStoreWeb.Controllers
{
    public class PastriesController : Controller
    {
        // GET: Pastries
        DBOperations db;

        public PastriesController()
        {
            db = new DBOperations();
        }

        public ActionResult Index()
        {
            var pastries = db.GetAllPastries();
            return View(pastries);
        }

        public ActionResult InTheStore()
        {
            var pastries = db.GetAllPastries().Where(pastr => pastr.Stock_ID == null).ToList();
            return View(pastries);
        }

        public ActionResult InTheStock()
        {
            var pastries = db.GetAllPastries().Where(pastr => pastr.Stock_ID != null).ToList();
            return View(pastries);
        }
    }
}

CandyStoreWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome";
}

<div class="jumbotron jumbotronWelcome">
    <h1>Welcome</h1>  
    <h2> to the candy store manager</h2>
</div>

CandyStoreWeb/Views/Home/SignIn.cshtml
@{
    ViewBag.Title = "Sign In";
}

@using (Html.BeginForm("SignIn", "Home", FormMethod.Post))
{
    <div class="row">
        <div class="loginForm col-xs-6 col-xs-offset-3 col-md-4 col-md-offset-4">
            <h2 class="text-center titleFont col-xs-12">Tasty Lary</h2>
            <input type="text" name="login" class="form-control text-center" style="margin:10px auto;" placeholder="Login" required autofocus>
            <input type="password" name="password" class="form-control text-center" style="margin:10px auto;" placeholder="Password" required>
            <button class="btn primaryColor primaryFont loginBtn col-xs-6 col-xs-offset-3 col-md-4 col-md-offset-4" type="submit">Sign in</button>
        </div>
    </div>
    if (CandyStoreWeb.Models.User.CurrentUser == null)
    {
        <div class="row">
            <div class="alert alert-danger col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3 text-center" role="alert">
                Invalid username or password
            </div>
        </div>
    }
}

CandyStoreWeb/Views/Orders/Create.cshtml
@model List<DAL.Pastry>

@{
	ViewBag.Title = "Make order";
}

<h2>Make an order</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Order</h4>
		<hr />

		@for (int i = 0; i < Model.Count; i++)
		{
			@Html.Partial("PastryPanel", new ViewDataDictionary { { "Model", Model[i] }, { "Number", i } })
			@Html.HiddenFor(m => m[i].ID)
			@Html.HiddenFor(m => m[i].ManufactureDate)
			@Html.HiddenFor(m => m[i].OrderLines)
			@Html.HiddenFor(m => m[i].PastryType)
			@Html.HiddenFor(m => m[i].PastryType_ID)
			@Html.HiddenFor(m => m[i].Price)
			@Html.HiddenFor(m => m[i].PurchaseLines)
			@Html.HiddenFor(m => m[i].Stock)
			@Html.HiddenFor(m => m[i].ShelfLife)
			@Html.HiddenFor(m => m[i].Stock_ID)
		}

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Make an order" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

CandyStoreWeb/Views/Orders/Index.cshtml
@model IEnumerable<DAL.Order>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderLine_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status_ID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderLine_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status_ID)
            </td>
            @if (CandyStoreWeb.Models.User.CurrentUser.Role == "Admin")
            {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }

</table>

CandyStoreWeb/Views/Pastries/InTheStock.cshtml
@model IEnumerable<DAL.Pastry>

@{
    ViewBag.Title = "InTheStock";
}

<h2>Pastries in the stock</h2>

@if (CandyStoreWeb.Models.User.CurrentUser.Role == "Admin")
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PastryType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShelfLife)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount.DiscountPercent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stock.Address)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PastryType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShelfLife)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount.DiscountPercent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock.Address)
            </td>
            @if (CandyStoreWeb.Models.User.CurrentUser.Role == "Admin")
            {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }

</table>

CandyStoreWeb/Views/Pastries/InTheStore.cshtml
@model IEnumerable<DAL.Pastry>

@{
    ViewBag.Title = "InTheStore";
}

<h2>Pastries in the store</h2>

@if (CandyStoreWeb.Models.User.CurrentUser.Role == "Admin")
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PastryType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShelfLife)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount.DiscountPercent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PastryType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShelfLife)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discount.DiscountPercent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManufactureDate)
        </td>
        @if (CandyStoreWeb.Models.User.CurrentUser.Role == "Admin")
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        }
    </tr>
    }

</table>

CandyStoreWeb/Views/Shared/PastryPanel.cshtml
<div class="col-xs-4 col-md-3">
	<div class="thumbnail text-center">
		<img src="~/Content/pastry.png" width="100" height="100" alt="...">
		<div class="caption">
			<h2>@ViewBag.Model.PastryType.Name</h2>
			<p>Quantity: @ViewBag.Model.Quantity</p>
			<p>Shelf life: @ViewBag.Model.ShelfLife day(s)</p>
			<p>Price: @ViewBag.Model.Price rub</p>
			<div class="input-group">
				<span class="input-group-btn">
					<button id="@ViewBag.Model.PastryType.Name" type="button" class="btn btn-default btn-number" data-type="minus" data-field="@ViewBag.Model.PastryType.ID">
						<span class="glyphicon glyphicon-minus"></span>
					</button>
				</span>
				<input type="text" name="[@ViewBag.Number].Quantity" id="@ViewBag.Model.PastryType.ID" class="form-control input-number" value="1" min="1" max="@ViewBag.Model.Quantity">
				<span class="input-group-btn">
					<button id="@ViewBag.Model.PastryType.Name" type="button" class="btn btn-default btn-number" data-type="plus" data-field="@ViewBag.Model.PastryType.ID">
						<span class="glyphicon glyphicon-plus"></span>
					</button>
				</span>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    $('#@ViewBag.Model.PastryType.Name').click(function (e) {
        e.preventDefault();

        fieldName = $(this).attr('data-field');
        type = $(this).attr('data-type');
        var input = $("input[id='" +  @ViewBag.Model.PastryType.ID + "']");
        var currentVal = parseInt(input.val());
        if (!isNaN(currentVal)) {
            if (type == 'minus') {

                if (currentVal > input.attr('min')) {
                    input.val(currentVal - 1).change();
                }
            } else if (type == 'plus') {

                if (currentVal < input.attr('max')) {
                    input.val(currentVal + 1).change();
                }
            }
        } else {
            input.val(0);
        }
    });
    $('.input-number').focusin(function () {
        $(this).data('oldValue', $(this).val());
    });
    $('.input-number').change(function () {

        minValue = parseInt($(this).attr('min'));
        maxValue = parseInt($(this).attr('max'));
        valueCurrent = parseInt($(this).val());

        name = $(this).attr('name');
        if (valueCurrent < minValue) {
            alert('Sorry, the minimum value was reached');
            $(this).val($(this).data('oldValue'));
        }
        else if (valueCurrent > maxValue) {
            alert('Sorry, the maximum value was reached');
            $(this).val($(this).data('oldValue'));
        }


    });
    $(".input-number").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
            // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) ||
            // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
            // let it happen, don't do anything
            return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });
</script>

CandyStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.slim.min.js"></script>

    <title>@ViewBag.Title – Tasty Lary</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="primaryColor">
    <div class="navbar navbar-inverse navbar-fixed-top darkColor">
        <div class="container">
            <div class="navbar-header" style="margin-right:30px">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="titleFont brand" href="@Url.Action("Index", "Home")">
                    <img src="~/Content/Logo.png" height="50" width="50" style="vertical-align:top" alt="" />
                    Tasty Lary
                </a>
            </div>
            <div class="navbar-collapse collapse">
                @if (CandyStoreWeb.Models.User.CurrentUser != null)
                {
                    <ul class="nav navbar-nav">
                        <li class="dropdown primaryFont">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pastries</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li class="dropdown-item" style="font-size:25px">@Html.ActionLink("In the store", "InTheStore", "Pastries")</li>
                                <li class="dropdown-item" style="font-size:25px">@Html.ActionLink("In the stock", "InTheStock", "Pastries")</li>
                            </ul>
                        </li>
                        <li class="primaryFont">@Html.ActionLink("Orders", "Index", "Orders")</li>
                        <li class="primaryFont">@Html.ActionLink("Discounts", "Index", "Discounts")</li>
                        <li class="primaryFont">@Html.ActionLink("Customers", "Index", "Customers")</li>
                    </ul>
                }
                <ul class="nav navbar-nav navbar-right">
                    @if (CandyStoreWeb.Models.User.CurrentUser == null)
                    {
                        <li class="primaryFont">@Html.ActionLink("Sign In", "SignIn", "Home")</li>
                    }
                    else
                    {
                        <li class="dropdown primaryFont">
                            <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@CandyStoreWeb.Models.User.CurrentUser.Name</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li class="dropdown-item" style="font-size:25px">@Html.ActionLink("Sign Out", "SignOut", "Home")</li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year – Candy Store Manager</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>